# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svNVFl_zuwCLW8mDt8z7XGcXaXEZV1-g
"""

import streamlit as st
st.write("welcome")